# Generated by cpp11: do not edit by hand

bcf_init_cpp <- function(univariate_treatment) {
  .Call(`_stochtree_bcf_init_cpp`, univariate_treatment)
}

bcf_add_train_with_weights_cpp <- function(bcf_wrapper, X_train_mu, X_train_tau, Z_train, y_train, weights_train, treatment_binary) {
  invisible(.Call(`_stochtree_bcf_add_train_with_weights_cpp`, bcf_wrapper, X_train_mu, X_train_tau, Z_train, y_train, weights_train, treatment_binary))
}

bcf_add_train_no_weights_cpp <- function(bcf_wrapper, X_train_mu, X_train_tau, Z_train, y_train, treatment_binary) {
  invisible(.Call(`_stochtree_bcf_add_train_no_weights_cpp`, bcf_wrapper, X_train_mu, X_train_tau, Z_train, y_train, treatment_binary))
}

bcf_add_test_cpp <- function(bcf_wrapper, X_test_mu, X_test_tau, Z_test) {
  invisible(.Call(`_stochtree_bcf_add_test_cpp`, bcf_wrapper, X_test_mu, X_test_tau, Z_test))
}

bcf_reset_global_var_samples_cpp <- function(bcf_wrapper, data_vector) {
  invisible(.Call(`_stochtree_bcf_reset_global_var_samples_cpp`, bcf_wrapper, data_vector))
}

bcf_reset_prognostic_leaf_var_samples_cpp <- function(bcf_wrapper, data_vector) {
  invisible(.Call(`_stochtree_bcf_reset_prognostic_leaf_var_samples_cpp`, bcf_wrapper, data_vector))
}

bcf_reset_treatment_leaf_var_samples_cpp <- function(bcf_wrapper, data_vector) {
  invisible(.Call(`_stochtree_bcf_reset_treatment_leaf_var_samples_cpp`, bcf_wrapper, data_vector))
}

bcf_reset_treatment_coding_samples_cpp <- function(bcf_wrapper, data_vector) {
  invisible(.Call(`_stochtree_bcf_reset_treatment_coding_samples_cpp`, bcf_wrapper, data_vector))
}

bcf_reset_control_coding_samples_cpp <- function(bcf_wrapper, data_vector) {
  invisible(.Call(`_stochtree_bcf_reset_control_coding_samples_cpp`, bcf_wrapper, data_vector))
}

bcf_reset_train_prediction_samples_cpp <- function(bcf_wrapper, muhat, tauhat, yhat, num_obs, num_samples, treatment_dim) {
  invisible(.Call(`_stochtree_bcf_reset_train_prediction_samples_cpp`, bcf_wrapper, muhat, tauhat, yhat, num_obs, num_samples, treatment_dim))
}

bcf_reset_test_prediction_samples_cpp <- function(bcf_wrapper, muhat, tauhat, yhat, num_obs, num_samples, treatment_dim) {
  invisible(.Call(`_stochtree_bcf_reset_test_prediction_samples_cpp`, bcf_wrapper, muhat, tauhat, yhat, num_obs, num_samples, treatment_dim))
}

sample_bcf_univariate_cpp <- function(bcf_wrapper, forest_samples_mu, forest_samples_tau, rng, cutpoint_grid_size, sigma_leaf_mu, sigma_leaf_tau, alpha_mu, alpha_tau, beta_mu, beta_tau, min_samples_leaf_mu, min_samples_leaf_tau, nu, lamb, a_leaf_mu, a_leaf_tau, b_leaf_mu, b_leaf_tau, sigma2, num_trees_mu, num_trees_tau, b1, b0, feature_types_mu_int, feature_types_tau_int, num_gfr, num_burnin, num_mcmc, leaf_init_mu, leaf_init_tau) {
  invisible(.Call(`_stochtree_sample_bcf_univariate_cpp`, bcf_wrapper, forest_samples_mu, forest_samples_tau, rng, cutpoint_grid_size, sigma_leaf_mu, sigma_leaf_tau, alpha_mu, alpha_tau, beta_mu, beta_tau, min_samples_leaf_mu, min_samples_leaf_tau, nu, lamb, a_leaf_mu, a_leaf_tau, b_leaf_mu, b_leaf_tau, sigma2, num_trees_mu, num_trees_tau, b1, b0, feature_types_mu_int, feature_types_tau_int, num_gfr, num_burnin, num_mcmc, leaf_init_mu, leaf_init_tau))
}

sample_bcf_multivariate_cpp <- function(bcf_wrapper, forest_samples_mu, forest_samples_tau, rng, cutpoint_grid_size, sigma_leaf_mu, sigma_leaf_tau_r, alpha_mu, alpha_tau, beta_mu, beta_tau, min_samples_leaf_mu, min_samples_leaf_tau, nu, lamb, a_leaf_mu, a_leaf_tau, b_leaf_mu, b_leaf_tau, sigma2, num_trees_mu, num_trees_tau, b1, b0, feature_types_mu_int, feature_types_tau_int, num_gfr, num_burnin, num_mcmc, leaf_init_mu, leaf_init_tau) {
  invisible(.Call(`_stochtree_sample_bcf_multivariate_cpp`, bcf_wrapper, forest_samples_mu, forest_samples_tau, rng, cutpoint_grid_size, sigma_leaf_mu, sigma_leaf_tau_r, alpha_mu, alpha_tau, beta_mu, beta_tau, min_samples_leaf_mu, min_samples_leaf_tau, nu, lamb, a_leaf_mu, a_leaf_tau, b_leaf_mu, b_leaf_tau, sigma2, num_trees_mu, num_trees_tau, b1, b0, feature_types_mu_int, feature_types_tau_int, num_gfr, num_burnin, num_mcmc, leaf_init_mu, leaf_init_tau))
}

create_forest_dataset_cpp <- function() {
  .Call(`_stochtree_create_forest_dataset_cpp`)
}

dataset_num_rows_cpp <- function(dataset) {
  .Call(`_stochtree_dataset_num_rows_cpp`, dataset)
}

dataset_num_covariates_cpp <- function(dataset) {
  .Call(`_stochtree_dataset_num_covariates_cpp`, dataset)
}

dataset_num_basis_cpp <- function(dataset) {
  .Call(`_stochtree_dataset_num_basis_cpp`, dataset)
}

dataset_has_basis_cpp <- function(dataset) {
  .Call(`_stochtree_dataset_has_basis_cpp`, dataset)
}

dataset_has_variance_weights_cpp <- function(dataset) {
  .Call(`_stochtree_dataset_has_variance_weights_cpp`, dataset)
}

forest_dataset_add_covariates_cpp <- function(dataset_ptr, covariates) {
  invisible(.Call(`_stochtree_forest_dataset_add_covariates_cpp`, dataset_ptr, covariates))
}

forest_dataset_add_basis_cpp <- function(dataset_ptr, basis) {
  invisible(.Call(`_stochtree_forest_dataset_add_basis_cpp`, dataset_ptr, basis))
}

forest_dataset_update_basis_cpp <- function(dataset_ptr, basis) {
  invisible(.Call(`_stochtree_forest_dataset_update_basis_cpp`, dataset_ptr, basis))
}

forest_dataset_add_weights_cpp <- function(dataset_ptr, weights) {
  invisible(.Call(`_stochtree_forest_dataset_add_weights_cpp`, dataset_ptr, weights))
}

create_column_vector_cpp <- function(outcome) {
  .Call(`_stochtree_create_column_vector_cpp`, outcome)
}

predict_forest_cpp <- function(forest_samples, dataset) {
  .Call(`_stochtree_predict_forest_cpp`, forest_samples, dataset)
}

predict_forest_raw_cpp <- function(forest_samples, dataset) {
  .Call(`_stochtree_predict_forest_raw_cpp`, forest_samples, dataset)
}

predict_forest_raw_single_forest_cpp <- function(forest_samples, dataset, forest_num) {
  .Call(`_stochtree_predict_forest_raw_single_forest_cpp`, forest_samples, dataset, forest_num)
}

sample_gfr_one_iteration_cpp <- function(data, residual, forest_samples, tracker, split_prior, rng, feature_types, cutpoint_grid_size, leaf_model_scale_input, variable_weights, global_variance, leaf_model_int, pre_initialized) {
  invisible(.Call(`_stochtree_sample_gfr_one_iteration_cpp`, data, residual, forest_samples, tracker, split_prior, rng, feature_types, cutpoint_grid_size, leaf_model_scale_input, variable_weights, global_variance, leaf_model_int, pre_initialized))
}

sample_mcmc_one_iteration_cpp <- function(data, residual, forest_samples, tracker, split_prior, rng, feature_types, cutpoint_grid_size, leaf_model_scale_input, variable_weights, global_variance, leaf_model_int, pre_initialized) {
  invisible(.Call(`_stochtree_sample_mcmc_one_iteration_cpp`, data, residual, forest_samples, tracker, split_prior, rng, feature_types, cutpoint_grid_size, leaf_model_scale_input, variable_weights, global_variance, leaf_model_int, pre_initialized))
}

sample_sigma2_one_iteration_cpp <- function(residual, rng, nu, lambda) {
  .Call(`_stochtree_sample_sigma2_one_iteration_cpp`, residual, rng, nu, lambda)
}

sample_tau_one_iteration_cpp <- function(forest_samples, rng, a, b, sample_num) {
  .Call(`_stochtree_sample_tau_one_iteration_cpp`, forest_samples, rng, a, b, sample_num)
}

rng_cpp <- function(random_seed) {
  .Call(`_stochtree_rng_cpp`, random_seed)
}

forest_container_cpp <- function(num_trees, output_dimension, is_leaf_constant) {
  .Call(`_stochtree_forest_container_cpp`, num_trees, output_dimension, is_leaf_constant)
}

num_samples_forest_container_cpp <- function(forest_samples) {
  .Call(`_stochtree_num_samples_forest_container_cpp`, forest_samples)
}

json_save_forest_container_cpp <- function(forest_samples, json_filename) {
  invisible(.Call(`_stochtree_json_save_forest_container_cpp`, forest_samples, json_filename))
}

json_load_forest_container_cpp <- function(forest_samples, json_filename) {
  invisible(.Call(`_stochtree_json_load_forest_container_cpp`, forest_samples, json_filename))
}

output_dimension_forest_container_cpp <- function(forest_samples) {
  .Call(`_stochtree_output_dimension_forest_container_cpp`, forest_samples)
}

is_leaf_constant_forest_container_cpp <- function(forest_samples) {
  .Call(`_stochtree_is_leaf_constant_forest_container_cpp`, forest_samples)
}

all_roots_forest_container_cpp <- function(forest_samples, forest_num) {
  .Call(`_stochtree_all_roots_forest_container_cpp`, forest_samples, forest_num)
}

add_sample_forest_container_cpp <- function(forest_samples) {
  invisible(.Call(`_stochtree_add_sample_forest_container_cpp`, forest_samples))
}

set_leaf_value_forest_container_cpp <- function(forest_samples, leaf_value) {
  invisible(.Call(`_stochtree_set_leaf_value_forest_container_cpp`, forest_samples, leaf_value))
}

set_leaf_vector_forest_container_cpp <- function(forest_samples, leaf_vector) {
  invisible(.Call(`_stochtree_set_leaf_vector_forest_container_cpp`, forest_samples, leaf_vector))
}

update_residual_forest_container_cpp <- function(data, residual, forest_samples, tracker, requires_basis, forest_num, add) {
  invisible(.Call(`_stochtree_update_residual_forest_container_cpp`, data, residual, forest_samples, tracker, requires_basis, forest_num, add))
}

tree_prior_cpp <- function(alpha, beta, min_samples_leaf) {
  .Call(`_stochtree_tree_prior_cpp`, alpha, beta, min_samples_leaf)
}

forest_tracker_cpp <- function(data, feature_types, num_trees, n) {
  .Call(`_stochtree_forest_tracker_cpp`, data, feature_types, num_trees, n)
}
