# Generated by cpp11: do not edit by hand

create_forest_dataset_cpp <- function() {
  .Call(`_stochtree_create_forest_dataset_cpp`)
}

dataset_num_rows_cpp <- function(dataset) {
  .Call(`_stochtree_dataset_num_rows_cpp`, dataset)
}

dataset_num_covariates_cpp <- function(dataset) {
  .Call(`_stochtree_dataset_num_covariates_cpp`, dataset)
}

dataset_num_basis_cpp <- function(dataset) {
  .Call(`_stochtree_dataset_num_basis_cpp`, dataset)
}

dataset_has_basis_cpp <- function(dataset) {
  .Call(`_stochtree_dataset_has_basis_cpp`, dataset)
}

dataset_has_variance_weights_cpp <- function(dataset) {
  .Call(`_stochtree_dataset_has_variance_weights_cpp`, dataset)
}

forest_dataset_add_covariates_cpp <- function(dataset_ptr, covariates) {
  invisible(.Call(`_stochtree_forest_dataset_add_covariates_cpp`, dataset_ptr, covariates))
}

forest_dataset_add_basis_cpp <- function(dataset_ptr, basis) {
  invisible(.Call(`_stochtree_forest_dataset_add_basis_cpp`, dataset_ptr, basis))
}

forest_dataset_update_basis_cpp <- function(dataset_ptr, basis) {
  invisible(.Call(`_stochtree_forest_dataset_update_basis_cpp`, dataset_ptr, basis))
}

forest_dataset_add_weights_cpp <- function(dataset_ptr, weights) {
  invisible(.Call(`_stochtree_forest_dataset_add_weights_cpp`, dataset_ptr, weights))
}

create_column_vector_cpp <- function(outcome) {
  .Call(`_stochtree_create_column_vector_cpp`, outcome)
}

create_rfx_dataset_cpp <- function() {
  .Call(`_stochtree_create_rfx_dataset_cpp`)
}

rfx_dataset_num_rows_cpp <- function(dataset) {
  .Call(`_stochtree_rfx_dataset_num_rows_cpp`, dataset)
}

rfx_dataset_has_group_labels_cpp <- function(dataset) {
  .Call(`_stochtree_rfx_dataset_has_group_labels_cpp`, dataset)
}

rfx_dataset_has_basis_cpp <- function(dataset) {
  .Call(`_stochtree_rfx_dataset_has_basis_cpp`, dataset)
}

rfx_dataset_has_variance_weights_cpp <- function(dataset) {
  .Call(`_stochtree_rfx_dataset_has_variance_weights_cpp`, dataset)
}

rfx_dataset_add_group_labels_cpp <- function(dataset_ptr, group_labels) {
  invisible(.Call(`_stochtree_rfx_dataset_add_group_labels_cpp`, dataset_ptr, group_labels))
}

rfx_dataset_add_basis_cpp <- function(dataset_ptr, basis) {
  invisible(.Call(`_stochtree_rfx_dataset_add_basis_cpp`, dataset_ptr, basis))
}

rfx_dataset_add_weights_cpp <- function(dataset_ptr, weights) {
  invisible(.Call(`_stochtree_rfx_dataset_add_weights_cpp`, dataset_ptr, weights))
}

predict_forest_cpp <- function(forest_samples, dataset) {
  .Call(`_stochtree_predict_forest_cpp`, forest_samples, dataset)
}

predict_forest_raw_cpp <- function(forest_samples, dataset) {
  .Call(`_stochtree_predict_forest_raw_cpp`, forest_samples, dataset)
}

predict_forest_raw_single_forest_cpp <- function(forest_samples, dataset, forest_num) {
  .Call(`_stochtree_predict_forest_raw_single_forest_cpp`, forest_samples, dataset, forest_num)
}

rfx_container_cpp <- function(num_components, num_groups) {
  .Call(`_stochtree_rfx_container_cpp`, num_components, num_groups)
}

rfx_model_cpp <- function(num_components, num_groups) {
  .Call(`_stochtree_rfx_model_cpp`, num_components, num_groups)
}

rfx_tracker_cpp <- function(group_labels) {
  .Call(`_stochtree_rfx_tracker_cpp`, group_labels)
}

rfx_label_mapper_cpp <- function(rfx_tracker) {
  .Call(`_stochtree_rfx_label_mapper_cpp`, rfx_tracker)
}

rfx_model_sample_random_effects_cpp <- function(rfx_model, rfx_dataset, residual, rfx_tracker, rfx_container, global_variance, rng) {
  invisible(.Call(`_stochtree_rfx_model_sample_random_effects_cpp`, rfx_model, rfx_dataset, residual, rfx_tracker, rfx_container, global_variance, rng))
}

rfx_container_predict_cpp <- function(rfx_container, rfx_dataset, label_mapper) {
  .Call(`_stochtree_rfx_container_predict_cpp`, rfx_container, rfx_dataset, label_mapper)
}

rfx_container_num_samples_cpp <- function(rfx_container) {
  .Call(`_stochtree_rfx_container_num_samples_cpp`, rfx_container)
}

rfx_container_num_components_cpp <- function(rfx_container) {
  .Call(`_stochtree_rfx_container_num_components_cpp`, rfx_container)
}

rfx_container_num_groups_cpp <- function(rfx_container) {
  .Call(`_stochtree_rfx_container_num_groups_cpp`, rfx_container)
}

rfx_model_set_working_parameter_cpp <- function(rfx_model, working_param_init) {
  invisible(.Call(`_stochtree_rfx_model_set_working_parameter_cpp`, rfx_model, working_param_init))
}

rfx_model_set_group_parameters_cpp <- function(rfx_model, group_params_init) {
  invisible(.Call(`_stochtree_rfx_model_set_group_parameters_cpp`, rfx_model, group_params_init))
}

rfx_model_set_working_parameter_covariance_cpp <- function(rfx_model, working_param_cov_init) {
  invisible(.Call(`_stochtree_rfx_model_set_working_parameter_covariance_cpp`, rfx_model, working_param_cov_init))
}

rfx_model_set_group_parameter_covariance_cpp <- function(rfx_model, group_param_cov_init) {
  invisible(.Call(`_stochtree_rfx_model_set_group_parameter_covariance_cpp`, rfx_model, group_param_cov_init))
}

rfx_model_set_variance_prior_shape_cpp <- function(rfx_model, shape) {
  invisible(.Call(`_stochtree_rfx_model_set_variance_prior_shape_cpp`, rfx_model, shape))
}

rfx_model_set_variance_prior_scale_cpp <- function(rfx_model, scale) {
  invisible(.Call(`_stochtree_rfx_model_set_variance_prior_scale_cpp`, rfx_model, scale))
}

rfx_tracker_get_unique_group_ids_cpp <- function(rfx_tracker) {
  .Call(`_stochtree_rfx_tracker_get_unique_group_ids_cpp`, rfx_tracker)
}

rfx_container_get_beta_cpp <- function(rfx_container_ptr) {
  .Call(`_stochtree_rfx_container_get_beta_cpp`, rfx_container_ptr)
}

rfx_container_get_alpha_cpp <- function(rfx_container_ptr) {
  .Call(`_stochtree_rfx_container_get_alpha_cpp`, rfx_container_ptr)
}

rfx_container_get_xi_cpp <- function(rfx_container_ptr) {
  .Call(`_stochtree_rfx_container_get_xi_cpp`, rfx_container_ptr)
}

rfx_container_get_sigma_cpp <- function(rfx_container_ptr) {
  .Call(`_stochtree_rfx_container_get_sigma_cpp`, rfx_container_ptr)
}

rfx_label_mapper_to_list_cpp <- function(label_mapper_ptr) {
  .Call(`_stochtree_rfx_label_mapper_to_list_cpp`, label_mapper_ptr)
}

sample_gfr_one_iteration_cpp <- function(data, residual, forest_samples, tracker, split_prior, rng, feature_types, cutpoint_grid_size, leaf_model_scale_input, variable_weights, global_variance, leaf_model_int, pre_initialized) {
  invisible(.Call(`_stochtree_sample_gfr_one_iteration_cpp`, data, residual, forest_samples, tracker, split_prior, rng, feature_types, cutpoint_grid_size, leaf_model_scale_input, variable_weights, global_variance, leaf_model_int, pre_initialized))
}

sample_mcmc_one_iteration_cpp <- function(data, residual, forest_samples, tracker, split_prior, rng, feature_types, cutpoint_grid_size, leaf_model_scale_input, variable_weights, global_variance, leaf_model_int, pre_initialized) {
  invisible(.Call(`_stochtree_sample_mcmc_one_iteration_cpp`, data, residual, forest_samples, tracker, split_prior, rng, feature_types, cutpoint_grid_size, leaf_model_scale_input, variable_weights, global_variance, leaf_model_int, pre_initialized))
}

sample_sigma2_one_iteration_cpp <- function(residual, rng, nu, lambda) {
  .Call(`_stochtree_sample_sigma2_one_iteration_cpp`, residual, rng, nu, lambda)
}

sample_tau_one_iteration_cpp <- function(forest_samples, rng, a, b, sample_num) {
  .Call(`_stochtree_sample_tau_one_iteration_cpp`, forest_samples, rng, a, b, sample_num)
}

rng_cpp <- function(random_seed) {
  .Call(`_stochtree_rng_cpp`, random_seed)
}

forest_container_cpp <- function(num_trees, output_dimension, is_leaf_constant) {
  .Call(`_stochtree_forest_container_cpp`, num_trees, output_dimension, is_leaf_constant)
}

num_samples_forest_container_cpp <- function(forest_samples) {
  .Call(`_stochtree_num_samples_forest_container_cpp`, forest_samples)
}

json_save_forest_container_cpp <- function(forest_samples, json_filename) {
  invisible(.Call(`_stochtree_json_save_forest_container_cpp`, forest_samples, json_filename))
}

json_load_forest_container_cpp <- function(forest_samples, json_filename) {
  invisible(.Call(`_stochtree_json_load_forest_container_cpp`, forest_samples, json_filename))
}

output_dimension_forest_container_cpp <- function(forest_samples) {
  .Call(`_stochtree_output_dimension_forest_container_cpp`, forest_samples)
}

is_leaf_constant_forest_container_cpp <- function(forest_samples) {
  .Call(`_stochtree_is_leaf_constant_forest_container_cpp`, forest_samples)
}

all_roots_forest_container_cpp <- function(forest_samples, forest_num) {
  .Call(`_stochtree_all_roots_forest_container_cpp`, forest_samples, forest_num)
}

add_sample_forest_container_cpp <- function(forest_samples) {
  invisible(.Call(`_stochtree_add_sample_forest_container_cpp`, forest_samples))
}

set_leaf_value_forest_container_cpp <- function(forest_samples, leaf_value) {
  invisible(.Call(`_stochtree_set_leaf_value_forest_container_cpp`, forest_samples, leaf_value))
}

set_leaf_vector_forest_container_cpp <- function(forest_samples, leaf_vector) {
  invisible(.Call(`_stochtree_set_leaf_vector_forest_container_cpp`, forest_samples, leaf_vector))
}

update_residual_forest_container_cpp <- function(data, residual, forest_samples, tracker, requires_basis, forest_num, add) {
  invisible(.Call(`_stochtree_update_residual_forest_container_cpp`, data, residual, forest_samples, tracker, requires_basis, forest_num, add))
}

tree_prior_cpp <- function(alpha, beta, min_samples_leaf) {
  .Call(`_stochtree_tree_prior_cpp`, alpha, beta, min_samples_leaf)
}

forest_tracker_cpp <- function(data, feature_types, num_trees, n) {
  .Call(`_stochtree_forest_tracker_cpp`, data, feature_types, num_trees, n)
}
